title: Chachigo.fr
markdown: kramdown

# for atom feed
author:
  name: Chachigo
  email: chachigo@duck.com

baseurl: "/chachigo.github.io "
url: "https://chachigo.github.io"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
